### ISSUE TITLE
Calendar is not showing iterations

### ISSUE THREAD

**Issue by iamkarlson** [Microsoft/vso-team-calendar#9]
I haven't found any settings for enable iterations in calendar
![screenshot_0220](https://cloud.githubusercontent.com/assets/4534374/9755267/a2dd9700-56e1-11e5-8ee7-00979d2e692d.png)
![screenshot_0213](https://cloud.githubusercontent.com/assets/4534374/9755269/a4dc3bf6-56e1-11e5-9284-d9cbbb434b2c.png)

**Comment by dmarcey** [comment]
You need to check the boxes next to the iterations to select them.

![image](https://cloud.githubusercontent.com/assets/5487287/9762547/5401cf52-56d2-11e5-84c9-f7f8b93f245f.png)


If you do, they will appear in the calendar like so:

![image](https://cloud.githubusercontent.com/assets/5487287/9762537/3f9b4cbe-56d2-11e5-8a79-a84bb3440c6e.png)

**Comment by iamkarlson** [comment]
Yes, I've found it. Thank you.
